# Generated by Django 2.1.3 on 2018-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHotel', '0003_tipohabitacion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
